### ISSUE TITLE
모바일에서 스티커 drag 안됨

### ISSUE THREAD

**Issue by kkjjhhbb** [GaeBTI/GBTI_FE#17]
Konva.js를 활용해 스티커를 드래그한 후 사이즈를 변경하거나 스티커를 돌리는 기능을 구현하다가
img 태그의 draggable 속성이 모바일에서 적용이 안되는 이슈를 발견함.

**Comment by kinnyeri** [comment]
tap 속성을 추가하여 모바일에서는 tap으로만 가능하게 하였음.
